"""add indexes and pagination-ready db improvements

Revision ID: 9b22dd62bfe1
Revises: 0c65a4f76152
Create Date: 2026-04-16 15:40:19.308669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b22dd62bfe1'
down_revision: Union[str, Sequence[str], None] = '0c65a4f76152'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_course_teacher_title', 'courses', ['teacher_id', 'title'], unique=False)
    op.create_index(op.f('ix_courses_teacher_id'), 'courses', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_enrollments_course_id'), 'enrollments', ['course_id'], unique=False)
    op.create_index(op.f('ix_enrollments_user_id'), 'enrollments', ['user_id'], unique=False)
    op.drop_constraint(op.f('sections_course_id_fkey'), 'sections', type_='foreignkey')
    op.create_foreign_key(None, 'sections', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sections', type_='foreignkey')
    op.create_foreign_key(op.f('sections_course_id_fkey'), 'sections', 'courses', ['course_id'], ['id'])
    op.drop_index(op.f('ix_enrollments_user_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_course_id'), table_name='enrollments')
    op.drop_index(op.f('ix_courses_teacher_id'), table_name='courses')
    op.drop_index('idx_course_teacher_title', table_name='courses')
    # ### end Alembic commands ###
